### INIT
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
  "req":{
    "type":"init",
    "pays":"tunisie"
  }
}

### More info concerning a single election
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
    "type":"election",
    "pays":"tunisie",
    "code_election":"tnleg2019"
}

### Participation rate
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
"req":{
  "type":"data",
  "code_election": "tnmun2018",
  "pays":"tunisie",
  "decoupage":"pays",
   "variables": [
     {"code_variable":"tp"}
   ]
}
}

### results of a single party for a singel election
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnleg2019",
  "decoupage": "gouvernorat",
  "variables": [
    {"code_variable":"prc","code_parti":"NAH"}
  ]
}
} 

### Requesting several variables, such as percentage and number of votes a single party received
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnac2011",
  "decoupage": "circonscription",
  "variables": [
    {"code_variable":"prc","code_parti":"ARD"},
    {"code_variable":"voix","code_parti":"ARD"}
  ]
}
} 

### Request a map
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
  "req":{
    "type":"map_decoupage",
    "pays":"Tunisie",
    "version":"10",
    "decoupages":["gouvernorat"]
  }
}

### Request an indicator
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
  "req":{
    "type":"indic",
    "pays":"tunisie",
    "ans":["2014"],
    "decoupage":"delegation",
    "indicateurs":["tnemp_actif_15p_ens_sup"]
  }
}

### Filter by governorate
POST https://manager.elyssa-project.org/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnmun2018",
  "decoupage": "delegation",
  "filtre":{
    "decoupage":"gouvernorat",
    "valeur":"11"
  },
  "variables": [
    {"code_variable":"prc","code_parti":"NIDA"}
  ]
}
} 

### Request a help entry
POST https://manager.elyssa-project.org/api
Content-Type: application/json


  {
    "type":"help",
    "id_1":"help"
  }