### INIT
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
  "req":{
    "type":"init",
    "pays":"Tunisie"
  }
}

### More info concerning a single election
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
  "req":{
    "type":"election",
    "pays":"tunisie",
    "code_election":"tnmun2018"
  }
}

###
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
"req":{
  "type":"data",
  "code_election": "*",
  "pays":"tunisie",
  "decoupage":"gouvernorat",
   "variables": [
     {"code_variable":"tp"}
   ]
}
}

###
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnmun2018",
  "decoupage": "gouvernorat",
  "variables": [
    {"code_variable":"prc","code_parti":"NIDA"}
  ]
}
} 

###
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnmun2018",
  "decoupage": "pays",
  "variables": [
    {"code_variable":"prc","code_parti":"*"}
  ]
}
} 

###
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnac2011",
  "decoupage": "gouvernorat",
  "variables": [
    {"code_variable":"prc","code_parti":"ARD"},
     {"code_variable":"voix","code_parti":"ARD"}
  ]
}
} 

###
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
"req":{
  "type": "data",
  "pays":"tunisie",
  "code_election": "tnmun2018",
  "decoupage": "gouvernorat",
  "variables": [
    {"code_variable":"tp"}
  ]
}
}

### Request a map
POST https://elyssa.tsaas.tn/api
Content-Type: application/json

{
  "req":{
    "type":"map_decoupage",
    "decoupages":["secteur"]
  }
}

